apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.name }} 
  {{- if .Values.mutatingWebhookConfiguration.annotations }}
  annotations:
    {{- toYaml .Values.mutatingWebhookConfiguration.annotations | nindent 4 }}
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: {{ .Values.caBundle }}
    service:
      name: simple-sidecar
      namespace: simple-sidecar
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: sidecar-injector.morven.me
  namespaceSelector:
    matchLabels:
      simple-sidecar.centml.ai/sidecar-injection: enabled
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
